AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla de CloudFormation para crear un bucket S3 con configuración personalizada.

Parameters:
  # Modifica el nombre del bucket aquí
  BucketName:
    Type: String
    Default: bucket-example01  # Puedes cambiar el nombre por el que desees, recuerda que debe ser único a nivel global
    Description: El nombre del bucket S3.
    
  # Habilitar o deshabilitar el versionado del bucket (Sí/No)
  EnableVersioning:
    Type: String
    Default: 'No'  # Si deseas habilitar el versionado, cambia el valor a 'Sí'
    AllowedValues:
      - 'Sí'
      - 'No'
    Description: Habilitar el versionado en el bucket (Sí/No).

  # Configuración de cifrado: 'S3' o 'KMS'
  EncryptionType:
    Type: String
    Default: 'KMS'  # Si deseas cifrado con S3, cambia este valor a 'S3'
    AllowedValues:
      - 'S3'
      - 'KMS'
    Description: Tipo de cifrado para los objetos del bucket (S3 o KMS).

  # Habilitar o deshabilitar las ACLs (Listas de control de acceso)
  EnableACL:
    Type: String
    Default: 'No'  # Si deseas habilitar las ACL, cambia el valor a 'Sí'
    AllowedValues:
      - 'Sí'
      - 'No'
    Description: Habilitar el uso de ACL (Sí/No).
  
  # Bloqueo de acceso público: Si deseas bloquear el acceso público, déjalo como 'Sí'
  BlockPublicAccess:
    Type: String
    Default: 'Sí'  # Si deseas permitir acceso público, cambia el valor a 'No'
    AllowedValues:
      - 'Sí'
      - 'No'
    Description: Bloquear acceso público al bucket (Sí/No).

  # Política de acceso personalizada: Si deseas cambiar la política, modifica este bloque.
  AccessPolicy:
    Type: String
    Default: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "Access-from-specific-user",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": [
              "arn:aws:s3:::bucket-example01",
              "arn:aws:s3:::bucket-example01/*"
            ],
            "Condition": {
              "ArnNotLike": {
                "aws:PrincipalArn": [
                  "arn:aws:iam::111111111111:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO",  # Reemplaza este ARN con el de tu rol de IAM o usuario
                  "arn:aws:iam::111111111111:user/userexample"  # Reemplaza este ARN con el de tu usuario de IAM
                ]
              }
            }
          }
        ]
      }
    Description: Política de acceso JSON para el bucket S3.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # Se utiliza el nombre proporcionado en los parámetros
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: !If [VersioningEnabled, 'Enabled', 'Suspended']  # No se habilita el versionado por defecto

      # Configuración de cifrado
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionMethod: 'aws:kms'  # Se utiliza KMS como método de cifrado
            KMSMasterKeyID: 'alias/aws/s3'  # Si deseas usar una clave KMS personalizada, reemplaza este valor por el ARN de tu clave KMS

      # Las ACL están deshabilitadas (configuración por defecto)
      AccessControl: !If [EnableACLYes, 'Private', 'Private']  # Las ACL están deshabilitadas y se configuran en 'Private'

      # Bloqueo de acceso público
      PublicAccessBlockConfiguration:
        BlockPublicAcls: !If [BlockPublicAccessYes, true, false]
        IgnorePublicAcls: !If [BlockPublicAccessYes, true, false]
        BlockPublicPolicy: !If [BlockPublicAccessYes, true, false]
        RestrictPublicBuckets: !If [BlockPublicAccessYes, true, false]

      # La política de acceso personalizada
      Policy: !Ref AccessPolicy

Conditions:
  # Condición para habilitar el versionado
  VersioningEnabled: !Equals [!Ref EnableVersioning, 'Sí']
  
  # Condición para activar el cifrado KMS
  EncryptionKMS: !Equals [!Ref EncryptionType, 'KMS']

  # Condición para habilitar ACLs
  EnableACLYes: !Equals [!Ref EnableACL, 'Sí']
  
  # Condición para bloquear el acceso público
  BlockPublicAccessYes: !Equals [!Ref BlockPublicAccess, 'Sí']

Outputs:
  # Salida con el nombre del bucket creado
  BucketName:
    Value: !Ref S3Bucket
    Description: El nombre del bucket S3 creado.
